### ISSUE TITLE
Lua Error start mit Job starten

### ISSUE THREAD

**Issue by HappyM89** [Courseplay/Courseplay_FS25#119]
### Version

8.0.0.1

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Helfer von Hof zu Feld 68 gesendet um dieses zu Pflügen.
Kurs auf Hof erstellt und auch dort im Course Editor gestartet.
Helfer ist aufs Feld gefahren am Ende der ersten Bahn beim Ausheben des Pfluges, kam dann die Error Meldung.

### Wie können wir diesen Fehler nachstellen?

Karte: River Springs
John Deere 7R mit Class Frontgewicht und Lizzard Untergrundlockerer 9m
Auf Feld 68 mit den Einstellungen aus den Screenshots, funktioniert auch wen man auf dem Feld steht und den Kurs erzeug. 

### Was hätte passieren sollen?

Keine Fehler meldung ;).
also es hat das Spiel erst mal nicht beeinträchtigt, und der Helfer hat seien Arbeit weiter gemacht.

### Bitte hänge deine log.txt an!

https://gist.github.com/HappyM89/7280085e56a6e2a31d6188e731d31603

mit Debug
https://gist.github.com/HappyM89/4b81a5ed92e974844f7e4491efc715a0

### Screenshots

![20241225234104_1](https://github.com/user-attachments/assets/90065d48-9487-467c-bd79-456f2522294c)
![20241225234112_1](https://github.com/user-attachments/assets/2294104e-31cb-4d9b-81e9-7fdd414c7c43)
![20241225234115_1](https://github.com/user-attachments/assets/4ee60e24-bcf9-4809-9391-0b8543bab7bb)
![20241225233859_1](https://github.com/user-attachments/assets/90425bd0-cfa0-480d-91c1-4a3d2cb019ba)

**Comment by KCHARRO** [comment]
I have two versions of the game 1.2 and 1.4 

This error was appearing since yesterday in 1.4

In 1.2, the worker starts working normally, but if you stop it it throws a LUA error in the file "CpAiWorker.lua" 

on line 348:       CpUtil.debugVehicle(CpDebug.DBG_FIELDWORK, self, "stop message: %s", message:getI18NText())

I replaced this: message:getI18NText())
            for this: message:getMessage(job))

remaining:        CpUtil.debugVehicle(CpDebug.DBG_FIELDWORK, self, "stop message: %s", message:getMessage(job))

This eliminated the error in both versions, now clean registry....

It only occasionally throws errors when doing something in the course generator menu, with the mouse... and even blocks the rotation of the camera, leaving and entering the vehicle returns to normal.

The log is from version 1.2, which is the one I play with, it may be useful for something.

[log.txt](https://github.com/user-attachments/files/18248410/log.txt)

The CP floating text window works normally...
![imagen](https://github.com/user-attachments/assets/ab76c4fc-af9e-4d6f-b7d9-33100fac0f9c)

In this, you can see in the log with Xerion Saddletrac that a course is generated, starts working and stops normally without errors....

![imagen](https://github.com/user-attachments/assets/03ff7a0e-cf52-470a-9b8d-2a231a9f4df0)

**Comment by pvaiko** [comment]
This has already been fixed by https://github.com/Courseplay/Courseplay_FS25/pull/101
